"""role em atendentes (RBAC)

Revision ID: afdc4396d689
Revises: 93f27a8a4c60
Create Date: 2026-07-11 20:39:25.969645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdc4396d689'
down_revision: Union[str, Sequence[str], None] = '93f27a8a4c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('atendentes', sa.Column('role', sa.String(length=20), server_default='atendente', nullable=False))
    # Data-fix (revisado à mão, ADR-014 R2): o atendente mais antigo do banco vira
    # admin para que exista pelo menos um perfil capaz de gerenciar os demais.
    # Subquery dupla exigida pelo MySQL (não permite UPDATE com SELECT da mesma
    # tabela direto); a forma também funciona em SQLite.
    op.execute(
        "UPDATE atendentes SET role='admin' "
        "WHERE id = (SELECT * FROM (SELECT MIN(id) FROM atendentes) AS t)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atendentes', 'role')
    # ### end Alembic commands ###
