"""lgpd confirmacao e leitura atendente

Revision ID: e9dd3dc323da
Revises: afdc4396d689
Create Date: 2026-07-11 22:38:53.607038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9dd3dc323da'
down_revision: Union[str, Sequence[str], None] = 'afdc4396d689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('exclusao_solicitada_em', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('ultima_leitura_atendente_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ultima_leitura_atendente_em')
    op.drop_column('usuarios', 'exclusao_solicitada_em')
    # ### end Alembic commands ###
